import assert from 'node:assert/strict';import {mkdirSync,writeFileSync} from 'node:fs';import {resolve} from 'node:path';import {chromium,devices} from 'playwright';import {startLab} from '../server.mjs';
const domOnly=process.env.LAB_DOM_ONLY==='1';const output=resolve('artifacts','screen-'+Date.now());mkdirSync(output,{recursive:true});const lab=await startLab({artifactDir:output,screenOnly:domOnly});const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/usr/bin/chromium',headless:true,args:['--no-sandbox','--use-fake-ui-for-media-stream','--use-fake-device-for-media-stream']});let count=0;
try{
 const context=await browser.newContext({...devices['iPhone 17 Pro'],serviceWorkers:'block'});const external=[],errors=[];await context.route('**/*',r=>{if(new URL(r.request().url()).origin!==lab.url){external.push(new URL(r.request().url()).hostname);return r.abort();}return r.continue();});await context.routeWebSocket(/.*/,s=>s.close());const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));
 await page.exposeFunction('__labDrive',async(kind,css,value)=>{const control=page.locator(css);if(kind==='fill')await control.fill(value);else if(kind==='select')await control.selectOption(value);else await control.click();});await page.exposeFunction('__labObserve',async data=>{if(data.caseFinished)await page.screenshot({path:resolve(output,String(++count).padStart(2,'0')+'-'+data.id+'-'+data.status+'.png')});});
 await page.goto(lab.url);await page.waitForFunction(()=>window.EpicureanLab?.run);await page.evaluate(()=>{for(const name of ['sendOrder','fireDiningCourse','fireIndependentLine','fireIndependentDining','fireDiningGroup','fireWorkingRow','fireNextCourse','confirmDiningAllergyFire','sendKitchenAllergyNote']){let blocked=false;try{window[name]();}catch(e){blocked=e.message.includes('disabled');}if(!blocked)throw Error('Direct invocation not blocked: '+name);const d=Object.getOwnPropertyDescriptor(window,name);if(d.writable)throw Error('Guard overwrite allowed: '+name);}EpicureanLab.reset();});await page.evaluate(dom=>{EpicureanLab.captureApproved=!dom;if(!dom)EpicureanLab.driver=window.__labDrive;EpicureanLab.observe=window.__labObserve;},domOnly);let report;if(domOnly){await page.locator('#lab-run').click();await page.waitForFunction(()=>EpicureanLab.report,null,{timeout:120000});report=await page.evaluate(()=>EpicureanLab.report);}else report=await page.evaluate(()=>EpicureanLab.run({includeAudio:true}));writeFileSync(resolve(output,'results.json'),JSON.stringify({...report,browser:'Chromium iPhone 17 Pro emulation',physicalDeviceTested:false,pageErrors:errors,externalRequests:external},null,2));
 assert.equal(errors.length,0,'Browser exceptions');assert.equal(external.length,0,'External request attempted');assert.ok(lab.reports.length,'Report not returned to Master');assert.ok(report.cases.every(c=>!c.actual.fbReady&&!c.actual.orders.length&&!c.actual.violations.length),'Isolation failed');
 console.log(JSON.stringify({output,summary:report.summary,cases:report.cases.map(c=>({id:c.id,status:c.status,error:c.error})),safety:'no external requests or sent orders'},null,2));if(report.summary.failed||report.summary.aborted)process.exitCode=1;
}finally{await browser.close();await lab.close();}
