/* Actual POS controls; synthetic DOM mode is explicitly NOT native phone automation. */
(function(){
 'use strict';const delay=ms=>new Promise(r=>setTimeout(r,ms));
 async function wait(fn,message,timeout=5000){const until=Date.now()+timeout;while(Date.now()<until){if(window.EpicureanLab?.abort)throw Error('Owner stopped suite');if(fn())return;await delay(30);}throw Error(message);}
 function assert(value,message){if(!value)throw Error(message);}
 function find(css){const all=Array.from(document.querySelectorAll(css)).filter(e=>e.getClientRects().length&&getComputedStyle(e).visibility!=='hidden');if(all.length!==1)throw Error('Expected one visible control: '+css+'; found '+all.length);return all[0];}
 async function act(kind,css,value){
  const lab=EpicureanLab;assert(!lab.abort,'Owner stopped suite');const el=find(css);el.scrollIntoView({block:'center',inline:'nearest'});await delay(60);
  const r=el.getBoundingClientRect(),x=Math.max(0,Math.min(innerWidth-1,r.x+r.width/2)),y=Math.max(0,Math.min(innerHeight-1,r.y+r.height/2)),cover=document.elementFromPoint(x,y);assert(r.width>0&&r.height>0&&(el.contains(cover)||cover?.contains(el)),'Control is obscured: '+css);
  lab.currentCase.steps.push({kind,selector:css,...(value!==undefined?{value}:{}),bounds:{x:r.x,y:r.y,w:r.width,h:r.height}});
  if(lab.driver)await lab.driver(kind,css,value);
  else if(kind==='fill'){el.value=value;el.dispatchEvent(new Event('input',{bubbles:true}));}
  else if(kind==='select'){el.value=value;el.dispatchEvent(new Event('change',{bubbles:true}));}
  else if(kind==='floor'){const args={bubbles:true,cancelable:true,pointerId:12,pointerType:'mouse',clientX:x,clientY:y,buttons:1};el.dispatchEvent(new PointerEvent('pointerdown',args));el.dispatchEvent(new PointerEvent('pointerup',{...args,buttons:0}));}
  else el.click();await delay(70);if(lab.observe)await lab.observe({kind,selector:css});
 }
 async function login(){for(const n of ['5','0','0','0'])await act('tap','#numpad button:nth-child('+(n==='5'?5:11)+')');await wait(()=>STATE.currentServer,'Visible PIN login failed');}
 async function openTable(){await act('tap','#app-content button[onclick="openTableService()"]');await wait(()=>document.querySelector('[data-table="14"]'),'Fixture floor table missing');await act('floor','[data-table="14"]');await wait(()=>document.querySelector('#order-top'),'Table did not open through floor control');}
 async function base(){await login();await openTable();}
 async function pricing(){await act('select','#voice-pricing-menu','pf_scalini_89');}
 async function voice(text){await act('fill','#voice-test-input',text);await act('tap','[data-voice-test] button');await wait(()=>EPICUREAN_ORDER_SESSION.state().phase!=='interpreting','Interpretation never completed');assert(STATE.voiceStatus,'Missing visible voice status');}
 async function confirm(){await act('tap','.voice-draft-acts button:first-child');await wait(()=>EPICUREAN_ORDER_SESSION.state().phase!=='interpreting','Confirmation never completed');}
 function visible(css,text){assert(find(css).innerText.toLowerCase().includes(text.toLowerCase()),'Actual screen missing '+JSON.stringify(text)+' in '+css);}
 const cases=[
  {id:'manual-menu',name:'Manual menu and authoritative price',run:async()=>{
   await base();await act('tap','.seat-chip[data-seat="2"]');await act('tap','.period-tabs button:nth-child(3)');if(!document.querySelector('#pf-overlay.show'))await act('tap','.ts-tile[onclick*="openPrixFixeSelector"]');
   const menu=EpicureanLab.fixture.menu;for(const [id,courseId] of [['sf_p_linguini','pfc_primi'],['sf_m_pork','pfc_main']]){const ci=menu.courses.findIndex(c=>c.id===courseId),oi=menu.courses[ci].options.findIndex(o=>o.id===id);await act('tap','label:has(input[name="pf-course-'+ci+'"][value="'+oi+'"])');if(id==='sf_m_pork')await act('tap','label:has(input[name="pf-temp-'+ci+'-'+oi+'"][value="Medium"])');}
   await act('tap','#pf-overlay .pf-sel-actions .send-btn');assert(STATE.currentOrder.length===1,'Manual menu did not create one line');assert(STATE.currentOrder[0].price===menu.price,'Manual price differs from BOH');visible('.toast-totals',String(menu.price));visible('.ts-check-lines','Linguini');visible('.ts-check-lines','pork');
  }},
  {id:'complete-correction',name:'Complete courses, vague/exact corrections, confirm and replay',run:async()=>{
   await base();await pricing();await voice('Foodmaster position 2A appetizer pescatore and main course pork chop medium');assert(!STATE.currentOrder.length,'Partial check written');assert(EPICUREAN_ORDER_SESSION.state().proposal.length===2,'Two courses not staged');visible('.voice-draft','Linguini');visible('.voice-draft','pork');visible('.voice-draft','Medium');
   await voice('Foodmaster No, change what you wrote');assert(EPICUREAN_ORDER_SESSION.state().phase==='clarify','No correction question');visible('.voice-draft','Which');await voice('Foodmaster replace the appetizer at position 2A with porcini ravioli');assert(EPICUREAN_ORDER_SESSION.state().proposal.length===2,'Correction duplicated course');visible('.voice-draft','Porcini');await confirm();assert(STATE.currentOrder.length===1,'Expected one menu');assert(STATE.currentOrder[0].price===EpicureanLab.fixture.menu.price,'Voice changed pricing');visible('.ts-check-lines','Porcini');visible('.ts-check-lines','pork');await voice('Foodmaster confirm');assert(STATE.currentOrder.length===1,'Replay duplicated menu');
  }},
  {id:'price-protection',name:'Price error and recovery with explicit menu',run:async()=>{
   await base();await voice('Foodmaster position 2A appetizer pescatore and main course pork chop medium');assert(!STATE.currentOrder.length,'Unpriced dishes changed check');assert(/standalone price|carte price/i.test(STATE.voiceStatus),'Missing price error');visible('.voice-draft','price');await pricing();await voice('Foodmaster position 2A appetizer pescatore and main course pork chop medium');await confirm();assert(STATE.currentOrder[0]?.price===EpicureanLab.fixture.menu.price,'Menu recovery failed');
  }},
  {id:'guest-conversation',name:'Guest chatter cannot order',run:async()=>{await base();await voice('I would like pork chop, what do you recommend for position 2A?');assert(!STATE.currentOrder.length&&!EPICUREAN_ORDER_SESSION.state().proposal.length,'Guest created order');visible('.voice-live-status','Conversation');}},
  {id:'logout-recovery',name:'Visible logout/login preserves draft and accepts new order',run:async()=>{
   await base();await pricing();await voice('Foodmaster position 2A appetizer pescatore and main course pork chop medium');await confirm();const id=STATE.currentOrder[0].lineId;await act('tap','#hh-top button[aria-label="Sign out"]');await wait(()=>!STATE.currentServer,'Logout failed');assert(!STATE.voiceSession.on,'Mic survived logout');await login();await openTable();await pricing();await voice('Foodmaster position 1 appetizer pescatore and main course pork chop medium');await confirm();assert(STATE.currentOrder.length===2,'Order after login failed');assert(STATE.currentOrder.some(l=>l.lineId===id),'Prior unsent menu lost');visible('.toast-totals',String(2*EpicureanLab.fixture.menu.price));
  }},
  {id:'audio-restart',audio:true,name:'Actual browser recording and audio HTTP after visible logout/login',run:async()=>{
   assert(EpicureanLab.captureApproved,'Native capture not owner-armed');await base();await pricing();EpicureanLab.audioFixture='two-course';await act('tap','[data-voice-mic] > button:first-child');await wait(()=>STATE._voiceRec?.recorder.state==='recording','Recorder failed to start');await delay(550);await act('tap','[data-voice-mic] > button:first-child');await wait(()=>EPICUREAN_ORDER_SESSION.state().phase==='review','Recorded clip did not produce review');visible('.voice-draft','pork');await confirm();await act('tap','#hh-top button[aria-label="Sign out"]');await wait(()=>!STATE.currentServer,'Logout failed');await login();await openTable();EpicureanLab.audioFixture='restart';await act('tap','[data-voice-mic] > button:first-child');await wait(()=>STATE._voiceRec?.recorder.state==='recording','Recorder did not restart after login');await delay(550);await act('tap','[data-voice-mic] > button:first-child');await wait(()=>STATE.voiceLastTranscript.includes('position 1'),'New clip did not reach transcription after login');assert(!STATE.voiceSession.on,'Mic session unexpectedly restarted');
  }},
  {id:'distinct-positions',name:'Both authoritative 2 and 2A remain distinct',issue:'POS_POSITION_IDENTITY',run:async()=>{await base();await pricing();await voice('Foodmaster position 2 appetizer pescatore, position 2A appetizer porcini');const p=EPICUREAN_ORDER_SESSION.state().proposal;assert(p.some(x=>x.seat==='2')&&p.some(x=>x.seat==='2A'),'POS rejected authoritative 2 / 2A: '+STATE.voiceStatus);}},
  {id:'dessert-later',name:'Actual BOH later-dessert choice is interpreted',issue:'POS_DESSERT_LATER',run:async()=>{await base();await pricing();await voice('Foodmaster position 2A dessert chocolate cake');assert(EPICUREAN_ORDER_SESSION.state().proposal.some(p=>p.itemId==='sf_d_cake'&&p.course===4),'POS did not stage later dessert: '+STATE.voiceStatus);}}
 ];
 async function run({only=null,includeAudio=false}={}){
  const lab=EpicureanLab;assert(lab.ready,'Fixture unavailable');if(lab.running)throw Error('Suite already running');lab.running=true;lab.abort=false;lab.report=null;const results=[],controls=document.getElementById('lab-controls');controls.hidden=true;
  try{
   for(const test of cases.filter(c=>(!only||only.includes(c.id))&&(!c.audio||includeAudio))){const item={id:test.id,name:test.name,status:'running',steps:[]};results.push(item);lab.currentCase=item;lab.reset();try{await test.run();assert(!fbReady,'Firebase isolation lost');assert(!STATE.orders.length,'Sent orders created');assert(!lab.snapshot().violations.length,'Disabled operation invoked');item.status='passed';}catch(e){item.status=lab.abort?'aborted':'failed';item.error=e.message;item.issue=test.issue||'SCREEN_WORKFLOW_FAILURE';}item.actual=lab.snapshot();item.screen={check:document.querySelector('.ts-check')?.innerText.slice(0,7000)||'',draft:document.querySelector('.voice-draft')?.innerText.slice(0,2500)||'',status:document.querySelector('.voice-live-status')?.innerText.slice(0,2500)||'',viewport:{width:innerWidth,height:innerHeight}};if(lab.observe)await lab.observe({caseFinished:true,id:test.id,status:item.status});if(lab.abort)break;}
   const report={schemaVersion:1,runId:'lab-'+Date.now()+'-'+Math.random().toString(16).slice(2,8),mode:'mock',interaction:lab.driver?'trusted-browser-driver':'synthetic-DOM-controls',physicalAcceptance:'NOT_ESTABLISHED',source:lab.fixture.manifest,cases:results,summary:{passed:results.filter(c=>c.status==='passed').length,failed:results.filter(c=>c.status==='failed').length,aborted:results.filter(c=>c.status==='aborted').length},limitations:['Scripted providers; no acoustic/language accuracy claim','DOM mode cannot prove native permissions or trusted gestures','Physical screenshot capture needs separately approved device automation']};await lab.fetchLocal('/lab/evidence',report);lab.report=report;return report;
  }finally{lab.running=false;controls.hidden=false;document.getElementById('lab-progress').textContent=lab.report?JSON.stringify(lab.report.summary):'Stopped or evidence-save error';}
 }
 window.addEventListener('DOMContentLoaded',async()=>{await wait(()=>window.EpicureanLab?.ready,'Lab bootstrap failed');EpicureanLab.run=run;EpicureanLab.caseIds=cases.map(c=>c.id);});
})();
